#!/usr/bin/env python3
"""Seed the ForgeOS database with demo data."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlmodel import Session, select
from database import engine, create_db_and_tables
from models import Project, Folder, Deliverable, Brief

def seed():
    create_db_and_tables()
    with Session(engine) as session:
        existing = session.exec(select(Project).where(Project.name == "Arize AI Launch Q3")).first()
        if existing:
            print("Already seeded. Skipping.")
            return

        project = Project(
            name="Arize AI Launch Q3",
            description="Product launches, content, and AR for Q3 2025",
        )
        session.add(project)
        session.commit()
        session.refresh(project)
        print(f"Created project: {project.name} (id={project.id})")

        folder = Folder(project_id=project.id, name="Phoenix 2.0 Launch")
        session.add(folder)
        session.commit()
        session.refresh(folder)
        print(f"Created folder: {folder.name} (id={folder.id})")

        brief = Brief(
            project_id=project.id,
            brief_md="""# Launch Brief: Phoenix 2.0

**Objective:** Announce Phoenix 2.0 to the developer community with emphasis on the new eval harness and agent tracing capabilities.

**Audience:** AI engineers and ML engineers building LLM-powered applications in production.

**Core Message:** Phoenix 2.0 makes it possible to evaluate agents systematically for the first time — not just individual LLM calls, but full multi-step agent runs.

**Supporting Points:**
- New eval harness for multi-step agent traces
- 10x faster trace ingestion
- Native OpenTelemetry support
- Works with any framework

**Proof Needed:** Real numbers on ingestion speed, a concrete before/after example of debugging an agent failure.

**Distribution:** Developer blog, HN launch post, LinkedIn, X, email to OSS community.
""",
            toggles_json='{"content_type": "blog", "voice": "technical", "brief_first": true}',
        )
        session.add(brief)
        session.commit()
        session.refresh(brief)
        print(f"Created brief (id={brief.id})")

        deliverable = Deliverable(
            folder_id=folder.id,
            content_type="blog",
            title="Phoenix 2.0: Evals for Agents, Not Just LLMs",
            status="draft",
            body_md="""# Phoenix 2.0: Evals for Agents, Not Just LLMs

*Draft — generated by ForgeOS seed*

The hardest part of building agents isn't the first run. It's knowing whether the 100th run worked the same way as the first.

Phoenix 2.0 ships today with a new eval harness designed specifically for multi-step agent traces.
""",
        )
        session.add(deliverable)
        session.commit()
        session.refresh(deliverable)

        brief.deliverable_id = deliverable.id
        session.add(brief)
        session.commit()
        print(f"Created deliverable: {deliverable.title} (id={deliverable.id})")

    print("\nSeed complete. Start the API and open http://localhost:3000 to see it.")

if __name__ == "__main__":
    seed()
